### ISSUE TITLE
create a develop branch 

### ISSUE THREAD

**Issue by autotelik** [EnvironmentAgency/digital-services-core#1]
I have created the master branch via first commit. Not sure procedure to create the develop

**Comment by Cruikshanks** [comment]
Having created master, locally run ```git flow init```. Leaving the branch names on their default it should leave you checked out on **develop** which will be a the same as **master**. Then immediately push **develop** and I can then set the repo to use it as the default branch.

**Comment by Cruikshanks** [comment]
Checked with @autotelik He is happy with is local environment and the repo now has a develop branch and is using that as its default.
