### ISSUE TITLE
Travis CI fails

### ISSUE THREAD

**Issue by autotelik** [EnvironmentAgency/digital-services-core#5]
Seems some sort of CI in place for this new engine but failed with 

"Could not find .travis.yml, using standard configuration."

Not sure if I need to add something ?

**Comment by Cruikshanks** [comment]
Having checked the build on [Travis-ci](https://travis-ci.org/EnvironmentAgency/digital-services-core/builds/67853771) that seemed to have fixed the issue with a missing ```.travis.yml``` file (which in turn caused an issue with the bundle install command) but now we are getting */home/travis/build/EnvironmentAgency/digital-services-core/spec/dummy/db/schema.rb doesn't exist yet. Run `rake db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /home/travis/build/EnvironmentAgency/digital-services-core/spec/dummy/config/application.rb to limit the frameworks that will be loaded.* Do I also need to tell travis-ci that a postgres database must be instantiated for this to work @autotelik ?

**Comment by autotelik** [comment]
The sandbox app under rspec uses sqlite3

The latest branches have migrations and therefore should contain a dummy/db/schema.rb

**Comment by Cruikshanks** [comment]
Integration with Travis-CI is now working. See c0a40ad0c875f8e313c00dbb0132c5c2d8d90f0e.
